export const OFUDA_FACTS: Record<string, string[]> = {
  en: [
    "I’ve spent more than half my life today inside a code editor. I’m starting to see the syntax when I close my eyes.",
    "705 commits on this portfolio alone. Every single one was a battle with my own perfectionism.",
    "I’ve watched Jujutsu Kaisen more than three times. Honestly, I’m still not over it.",
    "I’m currently watching the Jujutsu Kaisen Culling Game. If I'm slow to reply, you know why.",
    "Most people think I’m just a student, but actually, I’ve been building real systems while they were still learning loops.",
    "Building EyesOn feels like unfinished business. It’s the kind of project that keeps me up at night until the logic is perfect.",
    "Next.js over Vite. Always. I’m building for the world, not just my local machine.",
    "I’ve solved over 300 problems on LeetCode. Each one was a lesson in how much I still have to learn.",
    "When I’m stuck at 2 AM, I don't walk away. I sit here and explain the bug to an AI until the solution reveals itself.",
    "I write poetry with the same hands that write Go routines. Different languages, same intent.",
    "I sing when no one is listening. Usually Ed Sheeran. Usually 'Shape of You'.",
    "1,900 commits across all my projects. That’s a lot of late nights and cold coffee.",
    "I reduced 370MB of RAM usage to 90MB once. That feeling was better than any grade I've ever received.",
    "The Sixth Sense is my favorite movie. I love a story that makes you question everything you just saw.",
    "I grew up in Varanasi. The oldest city in the world. It gives you a different perspective on time.",
    "I've watched Death Note. It’s the reason I started questioning the 'obvious' solutions.",
    "My Hero Academia taught me that a 'quirk' is only a weakness if you don't know how to use it.",
    "I spent 14 hours straight on a Salesforce assignment once. I don't recommend it, but I’d do it again.",
    "I have an 8.87 CGPA. It looks good on paper, but the projects in my GitHub matter more to me.",
    "I taught myself Rust and Tauri just to see if I could. Turns out, I could.",
    "Varanasi is home. It’s where I learned that you can find peace even in total chaos.",
    "Breaking Bad. Game of Thrones. I’ve seen the greats. I’m still looking for a show that hits that hard again.",
    "I’m studying at Chandigarh University, but my real classroom is a terminal window.",
    "I once cleaned a dataset of 5,000 entries by hand. It was tedious, but the results were beautiful.",
    "Family Guy is my 'shut down' show. Even an engineer needs to laugh at something stupid sometimes.",
    "I built an AI that detects disease with 96% accuracy. That was the moment I realized code could save lives.",
    "I prefer Go for systems. It’s clean, it’s fast, and it doesn't try to be something it isn't.",
    "I use Tailwind CSS because I believe constraints actually make you more creative.",
    "My documentation is 20 pages long because if I can't explain it simply, I don't actually understand it.",
    "I built a Windows optimizer that the OS didn't even know it needed. I like making things run faster.",
    "I integrated the Shazam API into a project once just because I wanted to see how the math worked.",
    "Sub-200ms response times. If it's slower than that, I haven't finished the job.",
    "I’ve watched Dan Da Dan alone at 2 AM. It’s weird, it’s brilliant, and I’m not sure who to recommend it to yet.",
    "I handle 10,000+ records in IndexedDB without breaking a sweat. It’s all about the architecture.",
    "Most people think I’m quiet, but actually, I’m just thinking about a project I haven't started yet.",
    "Ed Sheeran has been my top artist for years. His songwriting is just... efficient.",
    "I used Python for data science, but my heart stays with Go and Rust.",
    "I have a minor in Data Science. I like finding the patterns in the noise.",
    "I’ve seen every episode of Breaking Bad. Walter White is a lesson in what happens when you let your ego lead.",
    "I don’t just write code; I ideate. 50% of my day is just thinking about the 'why' before the 'how'.",
    "I’ve made 747 commits to this very website. And I’m still not done.",
    "I once built a sync engine using Merkle Trees. That was a long week.",
    "The Culling Game arc in Jujutsu Kaisen is peak fiction. Change my mind.",
    "I sang 'Shape of You' for a whole hour once just to get the vocal runs right.",
    "I’ve watched more than ten anime series since I started in September 2025. I’m catching up fast.",
    "I built a platform for spiritual guidance. It’s funny how a programmer can help people find peace.",
    "I'm currently working on a project called EyesOn. It's the most ambitious thing I've tried yet.",
    "You’re reading this because I spent three hours perfecting the animation of this specific card.",
    "I built this. All of it. From the first line of Go to the last CSS keyframe. Welcome to my head."
  ],
  fr: [
    "J’ai passé plus de la moitié de ma vie aujourd’hui dans un éditeur de code. Je commence à voir la syntaxe quand je ferme les yeux.",
    "705 commits sur ce seul portfolio. Chacun était une bataille contre mon propre perfectionnisme.",
    "J’ai regardé Jujutsu Kaisen plus de trois fois. Honnêtement, je ne m’en suis toujours pas remis.",
    "Je regarde actuellement le Jujutsu Kaisen Culling Game. Si je tarde à répondre, vous savez pourquoi.",
    "La plupart des gens pensent que je ne suis qu'un étudiant, mais en fait, je construisais de vrais systèmes alors qu'ils apprenaient encore les boucles.",
    "Construire EyesOn ressemble à une affaire non résolue. C'est le genre de projet qui m'empêche de dormir jusqu'à ce que la logique soit parfaite.",
    "Next.js plutôt que Vite. Toujours. Je construis pour le monde, pas seulement pour ma machine locale.",
    "J’ai résolu plus de 300 problèmes sur LeetCode. Chacun était une leçon sur tout ce qu'il me reste à apprendre.",
    "Quand je suis coincé à 2 heures du matin, je ne m’en vais pas. Je reste ici et j'explique le bug à une IA jusqu'à ce que la solution se révèle.",
    "J'écris de la poésie avec les mêmes mains qui écrivent des routines Go. Différentes langues, même intention.",
    "Je chante quand personne n'écoute. Généralement du Ed Sheeran. Souvent 'Shape of You'.",
    "1 900 commits sur tous mes projets. Ça fait beaucoup de nuits blanches et de café froid.",
    "J’ai réduit une fois l’utilisation de la RAM de 370 Mo à 90 Mo. Ce sentiment était meilleur que n'importe quelle note que j'aie jamais reçue.",
    "Le Sixième Sens est mon film préféré. J'adore les histoires qui font remettre en question tout ce qu'on vient de voir.",
    "J'ai grandi à Varanasi. La plus vieille ville du monde. Ça donne une perspective différente sur le temps.",
    "J'ai regardé Death Note. C’est la raison pour laquelle j’ai commencé à remettre en question les solutions 'évidentes'.",
    "My Hero Academia m’a appris qu'une 'particularité' n'est une faiblesse que si l'on ne sait pas s'en servir.",
    "J'ai passé 14 heures d'affilée sur un devoir Salesforce une fois. Je ne le recommande pas, mais je le referais.",
    "J'ai un GPA de 8,87. C'est bien sur le papier, mais les projets sur mon GitHub comptent plus pour moi.",
    "J'ai appris seul le Rust et le Tauri juste pour voir si je pouvais. Il s'avère que je pouvais.",
    "Varanasi, c'est la maison. C'est là que j'ai appris qu'on peut trouver la paix même dans le chaos total.",
    "Breaking Bad. Game of Thrones. J’ai vu les plus grands. Je cherche encore une série qui me marque autant.",
    "J'étudie à l'Université de Chandigarh, mais ma vraie salle de classe est une fenêtre de terminal.",
    "J'ai nettoyé une fois un jeu de données de 5 000 entrées à la main. C'était fastidieux, mais les résultats étaient magnifiques.",
    "Family Guy est ma série 'détente'. Même un ingénieur a besoin de rire de quelque chose de stupide parfois.",
    "J'ai construit une IA qui détecte les maladies avec une précision de 96 %. C'est à ce moment-là que j'ai réalisé que le code pouvait sauver des vies.",
    "Je préfère Go pour les systèmes. C'est propre, c'est rapide, et ça ne cherche pas à être ce que ça n'est pas.",
    "J'utilise Tailwind CSS parce que je crois que les contraintes nous rendent plus créatifs.",
    "Ma documentation fait 20 pages car si je ne peux pas l'expliquer simplement, c'est que je ne la comprends pas vraiment.",
    "J'ai construit un optimiseur Windows dont l'OS ne savait même pas qu'il avait besoin. J'aime rendre les choses plus rapides.",
    "J'ai intégré l'API Shazam dans un projet une fois juste parce que je voulais voir comment fonctionnaient les maths.",
    "Temps de réponse inférieurs à 200 ms. Si c'est plus lent, c'est que je n'ai pas fini le travail.",
    "J’ai regardé Dan Da Dan seul à 2 heures du matin. C’est bizarre, c’est brillant, et je ne sais pas encore à qui le recommander.",
    "Je gère plus de 10 000 enregistrements dans IndexedDB sans difficulté. Tout est question d'architecture.",
    "La plupart des gens pensent que je suis calme, mais en fait, je pense juste à un projet que je n'ai pas encore commencé.",
    "Ed Sheeran est mon artiste préféré depuis des années. Son écriture est juste... efficace.",
    "J'ai utilisé Python pour la science des données, mais mon cœur reste avec Go et Rust.",
    "J'ai une mineure en science des données. J'aime trouver des motifs dans le bruit.",
    "J’ai vu tous les épisodes de Breaking Bad. Walter White est une leçon sur ce qui arrive quand on laisse son ego diriger.",
    "Je ne me contente pas d'écrire du code ; j'idéalise. 50 % de ma journée consistent à réfléchir au 'pourquoi' avant le 'comment'.",
    "J’ai fait 747 commits sur ce site web. Et je n’ai pas encore fini.",
    "J'ai construit une fois un moteur de synchronisation utilisant des arbres de Merkle. C'était une longue semaine.",
    "L'arc Culling Game dans Jujutsu Kaisen est le sommet de la fiction. Dites-moi le contraire.",
    "J'ai chanté 'Shape of You' pendant une heure entière juste pour maîtriser les envolées vocales.",
    "J'ai regardé plus de dix séries animées depuis mes débuts en septembre 2025. Je rattrape mon retard rapidement.",
    "J'ai construit une plateforme de guidance spirituelle. C'est amusant de voir comment un programmeur peut aider les gens à trouver la paix.",
    "Je travaille actuellement sur un projet appelé EyesOn. C'est la chose la plus ambitieuse que j'aie essayée jusqu'à présent.",
    "Vous lisez ceci parce que j'ai passé trois heures à perfectionner l'animation de cette carte spécifique.",
    "J'ai construit ceci. Tout ceci. De la première ligne de Go à la dernière keyframe CSS. Bienvenue dans ma tête."
  ],
  id: [
    "Saya telah menghabiskan lebih dari separuh hidup saya hari ini di dalam editor kode. Saya mulai melihat sintaks saat saya memejamkan mata.",
    "705 commit pada portofolio ini saja. Setiap satu commit adalah pertarungan dengan perfeksionisme saya sendiri.",
    "Saya telah menonton Jujutsu Kaisen lebih dari tiga kali. Sejujurnya, saya masih belum bisa melupakannya.",
    "Saat ini saya sedang menonton Jujutsu Kaisen Culling Game. Jika saya lambat membalas, Anda tahu alasannya.",
    "Kebanyakan orang mengira saya hanyalah seorang pelajar, padahal sebenarnya, saya telah membangun sistem nyata saat mereka masih belajar tentang perulangan.",
    "Membangun EyesOn terasa seperti urusan yang belum selesai. Ini adalah jenis proyek yang membuat saya terjaga di malam hari sampai logikanya sempurna.",
    "Next.js di atas Vite. Selalu. Saya membangun untuk dunia, bukan hanya untuk komputer lokal saya.",
    "Saya telah menyelesaikan lebih dari 300 masalah di LeetCode. Masing-masing adalah pelajaran tentang betapa banyak yang masih harus saya pelajari.",
    "Saat saya terjebak jam 2 pagi, saya tidak menyerah. Saya duduk di sini dan menjelaskan bug tersebut kepada AI sampai solusinya terungkap.",
    "Saya menulis puisi dengan tangan yang sama yang menulis Go routine. Bahasa yang berbeda, niat yang sama.",
    "Saya bernyanyi saat tidak ada yang mendengarkan. Biasanya lagu Ed Sheeran. Biasanya 'Shape of You'.",
    "1.900 commit di semua proyek saya. Itu banyak menghabiskan malam dan kopi dingin.",
    "Saya pernah mengurangi penggunaan RAM dari 370MB menjadi 90MB. Perasaan itu lebih baik daripada nilai apa pun yang pernah saya terima.",
    "The Sixth Sense adalah film favorit saya. Saya suka cerita yang membuat Anda mempertanyakan semua yang baru saja Anda lihat.",
    "Saya besar di Varanasi. Kota tertua di dunia. Kota ini memberikan perspektif yang berbeda tentang waktu.",
    "Saya sudah menonton Death Note. Itulah alasan saya mulai mempertanyakan solusi yang 'jelas'.",
    "My Hero Academia mengajarkan saya bahwa 'bakat' hanya menjadi kelemahan jika Anda tidak tahu cara menggunakannya.",
    "Saya pernah menghabiskan 14 jam berturut-turut untuk tugas Salesforce. Saya tidak menyarankannya, tapi saya akan melakukannya lagi.",
    "Saya memiliki IPK 8.87. Itu terlihat bagus di atas kertas, tapi proyek di GitHub saya lebih penting bagi saya.",
    "Saya belajar sendiri Rust dan Tauri hanya untuk melihat apakah saya bisa. Ternyata, saya bisa.",
    "Varanasi adalah rumah. Di sanalah saya belajar bahwa Anda bisa menemukan kedamaian bahkan di tengah kekacauan total.",
    "Breaking Bad. Game of Thrones. Saya sudah menonton yang terbaik. Saya masih mencari acara yang bisa seberkesan itu lagi.",
    "Saya belajar di Universitas Chandigarh, tapi ruang kelas saya yang sebenarnya adalah jendela terminal.",
    "Saya pernah membersihkan dataset berisi 5.000 entri secara manual. Itu membosankan, tapi hasilnya indah.",
    "Family Guy adalah acara 'istirahat' saya. Bahkan seorang insinyur perlu menertawakan sesuatu yang bodoh sesekali.",
    "Saya membangun AI yang mendeteksi penyakit dengan akurasi 96%. Itulah saat saya menyadari bahwa kode bisa menyelamatkan nyawa.",
    "Saya lebih suka Go untuk sistem. Bersih, cepat, dan tidak mencoba menjadi sesuatu yang bukan aslinya.",
    "Saya menggunakan Tailwind CSS karena saya percaya bahwa batasan sebenarnya membuat Anda lebih kreatif.",
    "Dokumentasi saya panjangnya 20 halaman karena jika saya tidak bisa menjelaskannya secara sederhana, berarti saya belum benar-benar memahaminya.",
    "Saya membangun pengoptimal Windows yang bahkan tidak disadari oleh sistem operasinya. Saya suka membuat segala sesuatu berjalan lebih cepat.",
    "Saya pernah mengintegrasikan API Shazam ke dalam sebuah proyek hanya karena saya ingin melihat cara kerja matematikanya.",
    "Waktu respon sub-200ms. Jika lebih lambat dari itu, saya belum menyelesaikan pekerjaan saya.",
    "Saya menonton Dan Da Dan sendirian jam 2 pagi. Aneh, brilian, dan saya belum yakin siapa yang harus saya rekomendasikan untuk menontonnya.",
    "Saya menangani 10.000+ catatan di IndexedDB tanpa kesulitan. Semuanya tentang arsitektur.",
    "Banyak orang mengira saya pendiam, padahal sebenarnya, saya hanya sedang memikirkan proyek yang belum saya mulai.",
    "Ed Sheeran telah menjadi artis top saya selama bertahun-tahun. Penulisan lagunya sangat... efisien.",
    "Saya menggunakan Python untuk ilmu data, tapi hati saya tetap berada di Go dan Rust.",
    "Saya memiliki minor dalam Ilmu Data. Saya suka mencari pola di tengah kebisingan.",
    "Saya telah menonton setiap episode Breaking Bad. Walter White adalah pelajaran tentang apa yang terjadi jika Anda membiarkan ego memimpin.",
    "Saya tidak hanya menulis kode; saya berideasi. 50% hari saya hanya memikirkan 'mengapa' sebelum 'bagaimana'.",
    "Saya telah membuat 747 commit ke situs web ini. Dan saya masih belum selesai.",
    "Saya pernah membangun mesin sinkronisasi menggunakan Merkle Trees. Itu minggu yang panjang.",
    "Arc Culling Game di Jujutsu Kaisen adalah puncak fiksi. Ubah pikiran saya.",
    "Saya pernah menyanyikan 'Shape of You' selama satu jam penuh hanya untuk mendapatkan vokal yang tepat.",
    "Saya telah menonton lebih dari sepuluh seri anime sejak saya mulai pada September 2025. Saya mengejar ketertinggalan dengan cepat.",
    "Saya membangun platform untuk bimbingan spiritual. Lucu melihat bagaimana seorang programmer bisa membantu orang menemukan kedamaian.",
    "Saat ini saya sedang mengerjakan proyek bernama EyesOn. Ini adalah hal paling ambisius yang pernah saya coba.",
    "Anda sedang membaca ini karena saya menghabiskan tiga jam menyempurnakan animasi kartu khusus ini.",
    "Saya membangun ini. Semuanya. Dari baris pertama Go hingga keyframe CSS terakhir. Selamat datang di pikiran saya."
  ]
};

// Fallback logic for legacy languages
OFUDA_FACTS.ja = OFUDA_FACTS.en;
OFUDA_FACTS.ko = OFUDA_FACTS.en;
OFUDA_FACTS["zh-tw"] = OFUDA_FACTS.en;
OFUDA_FACTS.hi = OFUDA_FACTS.en;
