export const OFUDA_FACTS = [
  "I’ve spent more than half my life today inside a code editor. I’m starting to see the syntax when I close my eyes.",
  "705 commits on this portfolio alone. Every single one was a battle with my own perfectionism.",
  "I’ve watched Jujutsu Kaisen more than three times. Honestly, I’m still not over it.",
  "I’m currently watching the Jujutsu Kaisen Culling Game. If I'm slow to reply, you know why.",
  "Most people think I’m just a student, but actually, I’ve been building real systems while they were still learning loops.",
  "Building EyesOn feels like unfinished business. It’s the kind of project that keeps me up at night until the logic is perfect.",
  "Next.js over Vite. Always. I’m building for the world, not just my local machine.",
  "I’ve solved over 300 problems on LeetCode. Each one was a lesson in how much I still have to learn.",
  "When I’m stuck at 2 AM, I don't walk away. I sit here and explain the bug to an AI until the solution reveals itself.",
  "I write poetry with the same hands that write Go routines. Different languages, same intent.",
  "I sing when no one is listening. Usually Ed Sheeran. Usually 'Shape of You'.",
  "1,900 commits across all my projects. That’s a lot of late nights and cold coffee.",
  "I reduced 370MB of RAM usage to 90MB once. That feeling was better than any grade I've ever received.",
  "The Sixth Sense is my favorite movie. I love a story that makes you question everything you just saw.",
  "I grew up in Varanasi. The oldest city in the world. It gives you a different perspective on time.",
  "I've watched Death Note. It’s the reason I started questioning the 'obvious' solutions.",
  "My Hero Academia taught me that a 'quirk' is only a weakness if you don't know how to use it.",
  "I spent 14 hours straight on a Salesforce assignment once. I don't recommend it, but I’d do it again.",
  "I have an 8.87 CGPA. It looks good on paper, but the projects in my GitHub matter more to me.",
  "I taught myself Rust and Tauri just to see if I could. Turns out, I could.",
  "Varanasi is home. It’s where I learned that you can find peace even in total chaos.",
  "Breaking Bad. Game of Thrones. I’ve seen the greats. I’m still looking for a show that hits that hard again.",
  "I’m studying at Chandigarh University, but my real classroom is a terminal window.",
  "I once cleaned a dataset of 5,000 entries by hand. It was tedious, but the results were beautiful.",
  "Family Guy is my 'shut down' show. Even an engineer needs to laugh at something stupid sometimes.",
  "I built an AI that detects disease with 96% accuracy. That was the moment I realized code could save lives.",
  "I prefer Go for systems. It’s clean, it’s fast, and it doesn't try to be something it isn't.",
  "I use Tailwind CSS because I believe constraints actually make you more creative.",
  "My documentation is 20 pages long because if I can't explain it simply, I don't actually understand it.",
  "I built a Windows optimizer that the OS didn't even know it needed. I like making things run faster.",
  "I integrated the Shazam API into a project once just because I wanted to see how the math worked.",
  "Sub-200ms response times. If it's slower than that, I haven't finished the job.",
  "I’ve watched Dan Da Dan alone at 2 AM. It’s weird, it’s brilliant, and I’m not sure who to recommend it to yet.",
  "I handle 10,000+ records in IndexedDB without breaking a sweat. It’s all about the architecture.",
  "Most people think I’m quiet, but actually, I’m just thinking about a project I haven't started yet.",
  "Ed Sheeran has been my top artist for years. His songwriting is just... efficient.",
  "I used Python for data science, but my heart stays with Go and Rust.",
  "I have a minor in Data Science. I like finding the patterns in the noise.",
  "I’ve seen every episode of Breaking Bad. Walter White is a lesson in what happens when you let your ego lead.",
  "I don’t just write code; I ideate. 50% of my day is just thinking about the 'why' before the 'how'.",
  "I’ve made 747 commits to this very website. And I’m still not done.",
  "I once built a sync engine using Merkle Trees. That was a long week.",
  "The Culling Game arc in Jujutsu Kaisen is peak fiction. Change my mind.",
  "I sang 'Shape of You' for a whole hour once just to get the vocal runs right.",
  "I’ve watched more than ten anime series since I started in September 2025. I’m catching up fast.",
  "I built a platform for spiritual guidance. It’s funny how a programmer can help people find peace.",
  "I'm currently working on a project called EyesOn. It's the most ambitious thing I've tried yet.",
  "You’re reading this because I spent three hours perfecting the animation of this specific card.",
  "I built this. All of it. From the first line of Go to the last CSS keyframe. Welcome to my head."
];
