export const OFUDA_FACTS = [
  "The one before you speaks Go. Not learned — absorbed.",
  "705 commits. Each one a quiet act of war.",
  "His code runs where browsers dare not — in WebAssembly.",
  "1,900 commits across all his projects. The machine never sleeps.",
  "He once reduced 370MB of RAM to 90. The machine thanked him.",
  "He is currently watching the Culling Game. Choose your battles wisely.",
  "More than ten anime. Each one left a mark.",
  "His favourite song is Shape of You. He has sung it more than he admits.",
  "Ed Sheeran lives rent-free in his head.",
  "The Sixth Sense is his favourite film. He saw the ending coming.",
  "He unwinds with Family Guy. Even architects need chaos.",
  "He has seen Breaking Bad. He understood the chemistry.",
  "He built an AI that detects disease with 96% accuracy. Medicine noticed.",
  "He writes poetry in the same hands that write Go routines.",
  "More than half his waking hours — spent building something that doesn't exist yet.",
  "EyesOn. His current obsession. Watch this space.",
  "He implemented Merkle Trees in a sync engine. Not because he had to — because it was right.",
  "Next.js, not Vite. Because he builds for the web, not just the dev server.",
  "8.87 CGPA. Academic Topper. The grades were never the goal — they followed.",
  "He studies AIML at Chandigarh University. The machines are learning. So is he.",
  "300+ problems solved on LeetCode. Pain is just another data structure.",
  "He carries Varanasi with him. The oldest city. The quietest confidence.",
  "He sings. In English. In Hindi. The language changes, the feeling doesn't.",
  "He taught himself Rust-Tauri to build what couldn't be built otherwise.",
  "His documentation site has 20+ pages. He cares that others understand.",
  "MobileNetV2. Transfer learning. He stood on the shoulders of giants — then climbed higher.",
  "Death Note changed something in him. He hasn't said what.",
  "My Hero Academia showed him that quirks aren't weaknesses.",
  "Da Da Dan. He watched it alone at 2AM. Recommended to no one yet.",
  "JJK lives in his chest. Gojo's absence hit different.",
  "He handled 10,000+ records in IndexedDB without flinching.",
  "Sub-200ms. That is his standard. Not a goal — a floor.",
  "He built a platform for spiritual guidance. The irony of a systems programmer speaking to the soul.",
  "Game of Thrones. He watched it all. He forgave the ending. Mostly.",
  "He interned at Celebal Technologies. 15+ components. 30% faster.",
  "Python for data. Go for systems. JavaScript for the world. He speaks all three fluently.",
  "He uses Tailwind CSS. Because constraints make better designers.",
  "He processes chaos. 5,000+ dataset entries cleaned with bare hands.",
  "He built a Windows optimizer that the OS didn't know it needed.",
  "He has a Data Science minor. He counts things others don't notice.",
  "C++ is in his past. The scars made him precise.",
  "Bash scripts run in the dark while he sleeps. They finish the work.",
  "He designed 15+ reusable components before he knew why that mattered.",
  "He studied moving averages to predict inventory. He applies the same logic to his own life.",
  "EcoQoS. He reduced CPU priority of background apps by 40%. Silence is productive.",
  "He integrated the Shazam API once. Music found a home in data.",
  "Sub-second navigation. Not a feature. A promise.",
  "He is early-career. The word 'early' is doing a lot of heavy lifting.",
  "The portfolio you are looking at — still being rewritten. He ships and refines simultaneously.",
  "You opened this card. He built this card. Somewhere, that means something."
];
